VexCL: vex::SpMat< real, column_t, idx_t > Class Template Reference
vex::SpMat< real, column_t, idx_t > Class Template Reference
Sparse matrix in hybrid ELL-CSR format.
#include <spmat.hpp>
Inherits matrix_terminal.
Public Types
typedef real value_type
Public Member Functions
SpMat ()
Empty constructor.
SpMat (const std::vector< cl::CommandQueue > &queue, size_t n, size_t m, const idx_t *row, const column_t *col, const real *val)
Constructor.
void mul (const vex::vector< real > &x, vex::vector< real > &y, real alpha=1, bool append=false) const
Matrix-vector multiplication.
size_t rows () const
Number of rows.
size_t cols () const
Number of columns.
size_t nonzeros () const
Number of non-zero entries.
Detailed Description
template<typename real, typename column_t = size_t, typename idx_t = size_t>
class vex::SpMat< real, column_t, idx_t >
Sparse matrix in hybrid ELL-CSR format.
Constructor & Destructor Documentation
template<typename real , typename column_t , typename idx_t > vex::SpMat< real, column_t, idx_t >::SpMat (const std::vector< cl::CommandQueue > & queue, size_t n, size_t m, const idx_t * row, const column_t * col, const real * val)
Constructor.
Constructs GPU representation of the matrix. Input matrix is in CSR format. GPU matrix utilizes ELL format and is split equally across all compute devices. When there are more than one device, secondary queue can be used to perform transfer of ghost values across GPU boundaries in parallel with computation kernel.
Parameters
queue vector of queues. Each queue represents one compute device.
n number of rows in the matrix.
m number of cols in the matrix.
row row index into col and val vectors.
col column numbers of nonzero elements of the matrix.
val values of nonzero elements of the matrix.
References vex::qctx(), and vex::qdev().
Member Function Documentation
template<typename real , typename column_t , typename idx_t > void vex::SpMat< real, column_t, idx_t >::mul (const vex::vector< real > & x, vex::vector< real > & y, real alpha = 1, bool append = false) const
Matrix-vector multiplication.
Matrix vector multiplication (or) is performed in parallel on all registered compute devices. Ghost values of x are transfered across GPU boundaries as needed.
Parameters
x input vector.
y output vector.
alpha coefficient in front of matrix-vector product
append if set, matrix-vector product is appended to y. Otherwise, y is replaced with matrix-vector product.
References vex::alignup(), and vex::qctx().
Referenced by vex::device_spmv_perf().
The documentation for this class was generated from the following file:
spmat.hpp