vexcl: vex Namespace Reference
vex Namespace Reference
OpenCL convenience utilities.
Namespaces
namespace Filter
Device filters.
Classes
class Context
VexCL context holder.
class multivector
Container for several vex::vectors.
class profiler
Class for gathering and printing OpenCL and Host profiling info.
class Reductor
Parallel reduction of arbitrary expression.
class SpMatBase
Base class for sparse matrix.
class SpMat
Sparse matrix in ELL format.
class SpMatCCSR
Sparse matrix in CCSR format.
struct partitioning_scheme
Partitioning scheme for vectors and matrices.
struct expression
Base class for a member of an expression.
struct KernelGenerator
Default kernel generation helper.
struct KernelGenerator< T, typename std::enable_if< std::is_arithmetic< T >::value >::type >
Kernel generation helper for arithmetic types.
class vector
Device vector.
struct BinaryExpression
Expression template.
struct UserFunction< body, RetType(ArgType...)>
Custom user function.
Enumerations
enum ReductionKind { SUM = 0, MAX = 1, MIN = 2 }
Possible kinds of reduction.
Functions
template<class DevFilter = Filter::AllFilter>
std::vector< cl::Device > device_list (DevFilter filter=Filter::All)
Select devices by given criteria.
template<class DevFilter = Filter::AllFilter>
std::pair< std::vector
< cl::Context >, std::vector
< cl::CommandQueue > > queue_list (DevFilter filter=Filter::All, cl_command_queue_properties properties=0)
Create command queues on devices by given criteria.
std::ostream & operator<< (std::ostream &os, const std::vector< cl::Device > &device)
std::ostream & operator<< (std::ostream &os, const std::vector< cl::CommandQueue > &queue)
std::ostream & operator<< (std::ostream &os, const vex::Context &ctx)
template<class T , uint N>
void copy (const multivector< T, N > &mv, std::vector< T > &hv)
Copy multivector to host vector.
template<class T , uint N>
void copy (const std::vector< T > &hv, multivector< T, N > &mv)
Copy host vector to multivector.
template<class Expr >
std::enable_if
< Expr::is_multiexpression,
const typename Expr::subtype & >
::type extract_component (const Expr &expr, uint i)
template<class LHS , class RHS >
std::enable_if
< compatible_multiexpressions
< LHS, RHS >::value,
BinaryMultiExpression< LHS,
'+', RHS > >::type operator+ (const LHS &lhs, const RHS &rhs)
Sum of two expressions.
template<class LHS , class RHS >
std::enable_if
< compatible_multiexpressions
< LHS, RHS >::value,
BinaryMultiExpression< LHS,
'-', RHS > >::type operator- (const LHS &lhs, const RHS &rhs)
Difference of two expressions.
template<class LHS , class RHS >
std::enable_if
< compatible_multiexpressions
< LHS, RHS >::value,
BinaryMultiExpression< LHS,
'*', RHS > >::type operator* (const LHS &lhs, const RHS &rhs)
Product of two expressions.
template<class LHS , class RHS >
std::enable_if
< compatible_multiexpressions
< LHS, RHS >::value,
BinaryMultiExpression< LHS,
'/', RHS > >::type operator/ (const LHS &lhs, const RHS &rhs)
Division of two expressions.
std::ostream & operator<< (std::ostream &os, profiler &prof)
template<typename real , typename column_t >
SpMV< real, column_t > operator* (const SpMatBase< real, column_t > &A, const vex::vector< real > &x)
Multiply sparse matrix and a vector.
template<class Expr , typename real , typename column_t >
std::enable_if
< Expr::is_expression, ExSpMV
< Expr, real, column_t >
>::type operator+ (const Expr &expr, const SpMV< real, column_t > &spmv)
Add an expression and sparse matrix - vector product.
template<class Expr , typename real , typename column_t >
std::enable_if
< Expr::is_expression, ExSpMV
< Expr, real, column_t >
>::type operator- (const Expr &expr, const SpMV< real, column_t > &spmv)
Subtruct sparse matrix - vector product from an expression.
double device_spmv_perf (const cl::Context &context, const cl::Device &device, size_t test_size=64U)
Returns device weight after spmv test.
std::vector< size_t > partition_by_spmv_perf (size_t n, const std::vector< cl::CommandQueue > &queue)
Partitions vector wrt to vector performance of devices.
template<class T >
std::string type_name ()
Convert typename to string.
template<>
std::string type_name< float > ()
template<>
std::string type_name< double > ()
template<>
std::string type_name< int > ()
template<>
std::string type_name< char > ()
template<>
std::string type_name< uint > ()
template<>
std::string type_name< uchar > ()
template<>
std::string type_name< size_t > ()
template<>
std::string type_name< ptrdiff_t > ()
size_t nextpow2 (size_t x)
Return next power of 2.
size_t alignup (size_t n, size_t m=16U)
Align n to the next multiple of m.
std::vector< size_t > partition_by_vector_perf (size_t n, const std::vector< cl::CommandQueue > &queue)
Partitions vector wrt to vector performance of devices.
std::vector< size_t > partition_equally (size_t n, const std::vector< cl::CommandQueue > &queue)
Partitions vector equally.
cl::Program build_sources (const cl::Context &context, const std::string &source)
Create and build a program from source string.
size_t kernel_workgroup_size (const cl::Kernel &kernel, const std::vector< cl::Device > &device)
Get maximum possible workgroup size for given kernel.
template<class T >
void copy (const vex::vector< T > &dv, std::vector< T > &hv, cl_bool blocking=CL_TRUE)
Copy device vector to host vector.
template<class T >
void copy (const std::vector< T > &hv, vex::vector< T > &dv, cl_bool blocking=CL_TRUE)
Copy host vector to device vector.
template<class InputIterator , class OutputIterator >
std::enable_if< std::is_same
< typename
std::iterator_traits
< InputIterator >::value_type,
typename std::iterator_traits
< OutputIterator >::value_type >
::value &&stored_on_device
< InputIterator >::value
&&!stored_on_device
< OutputIterator >::value,
OutputIterator >::type copy (InputIterator first, InputIterator last, OutputIterator result, cl_bool blocking=CL_TRUE)
Copy range from device vector to host vector.
template<typename T >
void swap (vector< T > &x, vector< T > &y)
Swap two vectors.
template<class Expr >
constexpr bool all_expressions_valid ()
template<class Head , class... Expr>
constexpr std::enable_if
< sizeof...(Expr), bool >
::type all_expressions_valid ()
template<class Expr >
constexpr bool all_expressions_arithmetic ()
template<class Head , class... Expr>
constexpr std::enable_if
< sizeof...(Expr), bool >
::type all_expressions_arithmetic ()
double device_vector_perf (const cl::Context &context, const cl::Device &device, size_t test_size=1024U *1024U)
Returns device weight after simple bandwidth test.
Variables
std::string standard_kernel_header
struct vex::partitioning_scheme partition
Detailed Description
OpenCL convenience utilities.
Vector expression template library for OpenCL.
Function Documentation
template<class InputIterator , class OutputIterator > std::enable_if< std::is_same< typename std::iterator_traits< InputIterator >::value_type, typename std::iterator_traits< OutputIterator >::value_type >::value &&!stored_on_device< InputIterator >::value &&stored_on_device< OutputIterator >::value, OutputIterator >::type vex::copy (InputIterator first, InputIterator last, OutputIterator result, cl_bool blocking = CL_TRUE)
Copy range from device vector to host vector.
Copy range from host vector to device vector.
template<class DevFilter = Filter::AllFilter> std::vector<cl::Device> vex::device_list (DevFilter filter = Filter::All)
Select devices by given criteria.
Parameters:
filter Device filter functor. Functors may be combined with logical operators.
Returns:
list of devices satisfying the provided filter.
This example selects any GPU which supports double precision arithmetic:
 auto devices = device_list(
            Filter::Type(CL_DEVICE_TYPE_GPU) && Filter::DoublePrecision
            );
std::vector< size_t > vex::partition_by_spmv_perf (size_t n, const std::vector< cl::CommandQueue > & queue)
Partitions vector wrt to vector performance of devices.
Partitions vector wrt to spmv performance of devices.
Launches the following kernel on each device:
 a = b + c;
where a, b and c are device vectors. Each device gets portion of the vector proportional to the performance of this operation.
Launches the following kernel on each device:
 y = A * x;
where x and y are vectors, and A is matrix for 3D Poisson problem in square domain. Each device gets portion of the vector proportional to the performance of this operation.
References alignup(), and device_spmv_perf().
std::vector< size_t > vex::partition_by_vector_perf (size_t n, const std::vector< cl::CommandQueue > & queue)
Partitions vector wrt to vector performance of devices.
Launches the following kernel on each device:
 a = b + c;
where a, b and c are device vectors. Each device gets portion of the vector proportional to the performance of this operation.
References alignup(), and device_vector_perf().
template<class DevFilter = Filter::AllFilter> std::pair<std::vector<cl::Context>, std::vector<cl::CommandQueue> > vex::queue_list (DevFilter filter = Filter::All, cl_command_queue_properties properties = 0)
Create command queues on devices by given criteria.
Parameters:
filter Device filter functor. Functors may be combined with logical operators.
Returns:
list of queues accociated with selected devices.
See also:
device_list
Variable Documentation
std::string vex::standard_kernel_header
Initial value:
 std::string(
        "#if defined(cl_khr_fp64)\n"
        "#  pragma OPENCL EXTENSION cl_khr_fp64: enable\n"
        "#elif defined(cl_amd_fp64)\n"
        "#  pragma OPENCL EXTENSION cl_amd_fp64: enable\n"
        "#endif\n"
        )